Improved `avoid_late_keyword` to support ignoring the subtype of the node type (#157)
solid-software/solid_lints pull request #158
Opened 2024-04-15 12:19 UTC by Yarl745

* Fixed issue #157

2024-04-15 16:18 UTC, yurii-prykhodko-solid requested changes
General logic LGTM, great start!;
Implementation-wise -- I think we are relying on raw regexp/string matching too much here. We should try and leverage the static types and utilities that analyzer/ast provides us.

Here's some stuff we may be able to use:
- https://pub.dev/documentation/analyzer/latest/dart_ast_token/Keyword/DYNAMIC-constant.html
- https://pub.dev/documentation/analyzer/latest/dart_element_type/DynamicType-class.html
- https://pub.dev/documentation/analyzer/latest/dart_element_type_provider/TypeProvider/objectType.html
- https://pub.dev/documentation/analyzer/latest/dart_element_type/TypeParameterType-class.html

We should also be more vigorous about testing this. I've added a couple ideas, but I'm sure you can expand on them.

2024-04-15 16:18 UTC, yurii-prykhodko-solid commented on lint_test/avoid_late_keyword_test.dart
> +  late final Subscription<Map<dynamic, String>> subscription4;
```suggestion
  late final Subscription<Map<String, String>> subscription7; // no lint
```

2024-04-15 16:18 UTC, yurii-prykhodko-solid commented on lib/src/utils/types_utils.dart
> +    ignoredTypes = getIntersectionTypesFor(ignoredTypes: ignoredTypes);
Don't mutate argument variables.

```suggestion
    final intersectionIgnoredTypes = getIntersectionTypesFor(ignoredTypes: ignoredTypes);
```

2024-04-15 16:18 UTC, yurii-prykhodko-solid commented on lib/src/utils/types_utils.dart
> +  }
Nitpick: you can use `fold` or `reduce` over _baseTypesRegex to shorten this.

2024-04-15 16:18 UTC, yurii-prykhodko-solid commented on lib/src/utils/types_utils.dart
> +            null;
`any` instead of `firstWhereOrNull(...) != null`?

2024-04-16 15:19 UTC, Yarl745 commented on lib/src/utils/node_utils.dart
- Enhances the AST analysis capabilities for type-related nodes by introducing a `TypeAnalyzerNode` class.
- Extends `GeneralizingAstVisitor` to navigate and process AST nodes, focusing on type analysis.
- Includes functionalities such as identifying 'dynamic' and 'Object' types.
- Manages child nodes and incorporates factory constructors for initialization from strings or AST nodes.
- Provides utility methods like `isInclude` for node comparison.
- Integrates visitor patterns to handle named types effectively.

2024-04-16 15:31 UTC, Yarl745 commented on lib/src/utils/node_utils.dart
> +    if (this != node) return false;
Perhaps need to change the name of the method to `isSubtype`

2024-04-17 09:45 UTC, yurii-prykhodko-solid requested changes

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lib/src/lints/avoid_late_keyword/avoid_late_keyword_rule.dart
> -
We should probably keep this.

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lib/src/utils/node_utils.dart
> +}
Let's place this in a separate file, to limit `_NamedTypeFinder` visibility scope.

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lib/src/utils/node_utils.dart
> +  bool get isDynamic => tokenName == "dynamic";
?
```suggestion
  bool get isDynamic => this is DynamicType;
```

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lib/src/utils/node_utils.dart
> +  bool get isObject => tokenName == "Object";
?
```suggestion
  /// Checks if the current token name is 'Object'.
  bool get isObject => type.isDartCoreObject;
```

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lib/src/utils/types_utils.dart
> +  bool get hasGenericString => contains(_genericRegex);
seems unused
```suggestion
```

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lib/src/utils/node_utils.dart
> +  bool isSubtype({required NamedType node}) {
I think this name communicates more clearly the direction of the comparison.

```suggestion
  bool isSubtypeOf({required NamedType node}) {
```

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lint_test/avoid_late_keyword_allow_no_type_specified/avoid_late_keyword_allow_no_type_specified.dart
> +// ignore_for_file: prefer_const_declarations, unused_local_variable, prefer_match_file_name
move this to lint_test/avoid_late_keyword/no_generics_specified

2024-04-17 09:45 UTC, yurii-prykhodko-solid commented on lint_test/avoid_late_keyword_test.dart
lint_test/avoid_late_keyword/with_generics

2024-04-17 12:16 UTC, yurii-prykhodko-solid approved these changes
LGTM!

2024-04-18 14:28 UTC, illia-romanenko approved these changes
LGTM - thanks

2024-04-18 14:32 UTC, merged