Rename custom lints to use snake_case
solid-software/solid_lints pull request #66
Opened 2023-11-09 17:06 UTC by solid-vovabeloded

2023-11-09 17:20 UTC, yurii-prykhodko-solid commented on lib/lints/member_ordering/models/member_ordering_parameters.dart
>    static const _alphabetizeByTypeConfig = 'alphabetize-by-type';
?
```suggestion
  static const _alphabetizeByTypeConfig = 'alphabetize_by_type';
```

2023-11-09 17:21 UTC, illia-romanenko approved these changes
LGTM

2023-11-09 17:24 UTC, yurii-prykhodko-solid requested changes
All LGTM, except one missed spot.

2023-11-10 12:38 UTC, yurii-prykhodko-solid approved these changes
LGTM!

2023-11-10 13:00 UTC, merged